import asyncio
from typing import AsyncGenerator
from utils.agentstate import AgentState
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


async def stream_agent_response(state: AgentState, workflow , state_container) -> AsyncGenerator[str, None]:
    """Stream agent responses and updates."""
    try:
        final_state = state.copy()

        async for update in workflow.astream(state, stream_mode="updates", subgraphs=False):
            for _, node_state in update.items():

                if isinstance(node_state, dict):
                    final_state.update(node_state)

                agent_name = next(iter(update))
                agent_state = update.get(agent_name, {})
                print(agent_name)

                # --- Reasoning Agent ---
                if agent_name == "analyzer":
                    message = "🔍 Understanding your financial query and extracting logic...\n\n"
                    thinking = agent_state.get("Thinking", {})
                    message = ""

                    if isinstance(thinking, dict):
                        message = thinking.get("reasoning", "")
                    elif isinstance(thinking, str):
                        message = thinking

                    for char in message:
                        yield char
                        await asyncio.sleep(0.015)
                    yield "\n\n"

                # --- Code Generation Agent ---
                elif agent_name == "code_generator":
                    message = "🧠 Translating reasoning into executable analysis steps...\n\n"
                    thinking = agent_state.get("Thinking", {})

                    if isinstance(thinking, dict):
                        message += thinking.get("reasoning", "")

                    elif isinstance(thinking, str):
                        message += thinking

                    for char in message:
                        yield char
                        await asyncio.sleep(0.015)
                    yield "\n\n"

                # --- Code Executor Agent ---
                elif agent_name == "executor":
                    message = "Executing the code generated by the code generation agent..\n\n"
                    message += agent_state.get("Thinking")["reasoning"]
                    for char in message:
                        yield char
                        await asyncio.sleep(0.015)

                    # If execution failed, surface error early
                    if isinstance(agent_state.get("result"), str) and "Error" in agent_state["result"]:
                        yield "\n\n❌ Execution failed. Please review the error details.\n"
                    else:
                        yield "\n\n"

                # --- Plot Recommender ---
                elif agent_name == "plot_recommender":
                    message = "📊 Identifying the most insightful visualizations...\n\n"
                    message += "\n"+ agent_state.get("Thinking")["reasoning"]
                    for char in message:
                        yield char
                        await asyncio.sleep(0.015)
                    yield "\n\n"

                # --- Plot Code Generation ---
                elif agent_name == "plot_code_generation":
                    message = "🖼️ Generating visualization logic..."
                    message += "\n"+ agent_state.get("Thinking")["reasoning"]
                    for char in message:
                        yield char
                        await asyncio.sleep(0.015)
                    yield "\n\n"

                # --- Plot Executor ---
                elif agent_name == "plot_executor_agent":
                    message = "📈 Rendering charts for better insights..."
                    message += "\n"+ agent_state.get("Thinking")["reasoning"]
                    for char in message:
                        yield char
                        await asyncio.sleep(0.015)
                    yield "\n\n"

                # --- Final Response Generator ---
                elif agent_name == "response_generator":
                    final_message = "✅ Analysis complete. Here’s what we found:\n\n"
                    for char in final_message:
                        yield char
                        await asyncio.sleep(0.01)

                    # Stream final assistant message (if present)
                    messages = agent_state.get("messages", [])
                    if messages:
                        last_msg = messages[-1]
                        if hasattr(last_msg, "content"):
                            for char in last_msg.content:
                                yield char
                                await asyncio.sleep(0.005)

                    yield "\n"

        if state_container is not None:
            state_container['final_state'] = final_state
    
    except Exception as e:
        error_msg = f"\n❌ Error processing query: {str(e)}"
        logger.error(error_msg, exc_info=True)
        yield error_msg